# Generated by Django 3.2.14 on 2022-08-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_book_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='price_excl_tax',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='price_incl_tax',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='product_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='tax',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='upc',
            field=models.CharField(max_length=200),
        ),
    ]
